spring:
  application:
    name: shift-master

  datasource:
    url: jdbc:mysql://localhost:3306/shift_master
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true